services:
  quarkus-petclinic:
    build:
      context: .
      dockerfile: src/main/docker/Containerfile
    image: quarkus-petclinic:latest
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-petclinic-db:5432/mydb
    ports:
      - "8080:8080"
    depends_on:
      quarkus-petclinic-db:
        condition: service_healthy

  quarkus-petclinic-db:
    image: "postgres:14"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
