ARG agent_version

FROM quay.io/cryostat/cryostat-agent-init:${agent_version} AS agent

FROM quay.io/wildfly/wildfly:23.0.2.Final
COPY --from=agent /cryostat/agent/cryostat-agent-shaded.jar /opt/cryostat/cryostat-agent.jar
