ARG server_img=docker.io/itzg/minecraft-server:java21-jdk
ARG agent_version

FROM quay.io/cryostat/cryostat-agent-init:${agent_version} AS agent

FROM ${server_img}
COPY --from=agent /cryostat/agent/cryostat-agent-shaded.jar /opt/cryostat/agent.jar
