####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Before building the container image run:
#
# ./mvnw package
#
# Then, build the image with:
#
# docker build -f src/main/docker/Containerfile -t quarkus-petclinic:latest .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus-petclinic
###
FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.21-1.1737580425

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
EXPOSE 8080
USER 185

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

COPY --chown=185 target/quarkus-petclinic-*-runner.jar /deployments/quarkus-run.jar
