ARG agent_version

FROM quay.io/cryostat/cryostat-agent-init:${agent_version} AS agent
FROM docker.io/library/eclipse-temurin:25-jre-jammy

WORKDIR /opt
COPY --from=agent /cryostat/agent/cryostat-agent-shaded.jar /opt/cryostat/cryostat-agent.jar
COPY ./Hello.class /opt/
CMD java -javaagent:/opt/cryostat-agent.jar Hello
