ARG agent_version

FROM quay.io/andrewazores/cryostat-agent-init:${agent_version} AS agent

FROM quay.io/wildfly/wildfly:28.0.1.Final-jdk17
COPY --from=agent /cryostat/agent/cryostat-agent-shaded.jar /opt/cryostat/cryostat-agent.jar
