name: Build Container Images

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # every Monday at midnight
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

env:
  OPENSUSE_UNOFFICIAL_LIBCONTAINERS_KEY_URL: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/Release.key"
  OPENSUSE_UNOFFICIAL_LIBCONTAINERS_SOURCE_URL: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04"
  CI_USER: redhat-java-monitoring+github_ci
  CI_REGISTRY: quay.io
  CI_NAMESPACE: redhat-java-monitoring

jobs:
  get-agent-version:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'cryostatio' }}
    outputs:
      image-version: ${{ steps.get-agent-version.outputs.agent-version }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/cryostat-agent
        ref: ${{ github.ref }}
        submodules: true
        fetch-depth: 0
    - id: get-agent-version
      run: |
        echo "agent-version=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)" >> $GITHUB_OUTPUT

  get-samples:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'cryostatio' }}
    outputs:
      paths: ${{ steps.get-paths.outputs.paths }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        submodules: true
        fetch-depth: 0
    - id: get-paths
      run: |
        paths=$(find . -mindepth 2 -type f -name build.bash | awk '{print "\x27" $1 "\x27"}' | head -c -1 | tr '\n' ',')
        echo "paths=[${paths}]" >> "$GITHUB_OUTPUT"

  build-and-push:
    needs: [get-agent-version, get-samples]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJSON(needs.get-samples.outputs.paths) }}
    env:
      agent-version: ${{ needs.get-agent-version.outputs.image-version }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Install qemu
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Get date tag
      run: echo "DATE_TAG=$(date -uI)" >> "$GITHUB_ENV"
    - name: Registry login
      run: podman login quay.io --username=${{ env.CI_USER }} --password=${{ secrets.REPOSITORY_TOKEN }}
    - name: Build application
      run: bash ${{ matrix.path }}
      env:
        TAGS: ${{ env.agent-version }} ${{env.DATE_TAG}} latest
        PUSH_MANIFEST: true
        APP_REGISTRY: ${{ env.CI_REGISTRY }}
        APP_NAMESPACE: ${{ env.CI_NAMESPACE }}
        BUILD_TAG: ${{ env.agent-version }}
        CRYOSTAT_AGENT_VERSION: ${{ env.agent-version }}
